DROP USER biblioteca_DSIS4 CASCADE;

CREATE USER biblioteca_DSIS4 IDENTIFIED BY 123 
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
quota 10m ON users;

GRANT CREATE SESSION TO
biblioteca_DSIS4;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER
TO biblioteca_DSIS4;

GRANT CREATE SEQUENCE TO biblioteca_DSIS4;


